### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [scottrhoyt/SwiftyTextTable#10]
I'd be cool to also add CocoaPods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by scottrhoyt** [comment]
Thanks @lfarah. I've been a bit partial to Carthage for Swift development, but if this issue generates enough interest, I'd be happy to do CocoaPods as well.
