### ISSUE TITLE
Run unit tests with SPM

### ISSUE THREAD

**Issue by norio-nomura** [scottrhoyt/SwiftyTextTable#3]

**Comment by scottrhoyt** [comment]
Thanks! I'm going to have to look at how you set that up on SwiftLint! :+1:

**Comment by scottrhoyt** [comment]
I was hoping to get this working with the release of Swift 2.2. However seeing as the SPM wasn't included in either Linux or OS X, Swift Core wasn't included in Linux, and the development snapshots break things often, I don't know if it makes any sense to do so at the moment. @norio-nomura if you have any thoughts from what you have tried on SwiftLint, I'd be all ears.

**Comment by norio-nomura** [comment]
`swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a` is last version that can build codes written for swift-2.x and includes SPM.
For adapting `swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a` or later, we need to rewrite codes for supporting swift-3 API. I don't know whether we can keep single branch with supporting both of swift-2.x and swift-3 API by conditional compiling or need separating branches.
Maybe we should open another issue for supporting swift-3 API.

Now, I confirmed again that SwiftyTextTable-0.3.0 passes `swift test` with `swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a` and close this issue.

@scottrhoyt @jpsim Thanks! :pray:
