### ISSUE TITLE
Swift 4.2 Carthage

### ISSUE THREAD

**Issue by arguiot** [scottrhoyt/SwiftyTextTable#34]
I'm trying to use SwiftyTextTable using Carthage on macOS Mojave, with Xcode 10 that uses Swift 4.2, and I'm getting the following error:

```
*** Cloning SwiftyTextTable
*** Checking out SwiftyTextTable at "0.8.2"
*** xcodebuild output can be found in /var/folders/9t/kjmwgng518vcjnczl_0j9h780000gn/T/carthage-xcodebuild.R3VNUw.log
*** Downloading SwiftyTextTable.framework binary at "0.8.2"
***  Skipped installing SwiftyTextTable.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source
*** Building scheme "SwiftyTextTable" in SwiftyTextTable.xcodeproj
```

**Comment by Roslund** [comment]
Chartage is just informing you that the binary version of the framework is built with swift 4.1.2. 
Since you are using swift 4.2 Chartage builds the package from source. Based on your output everything should be working fine. I'm happy to help if you have any other problems.
